name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteorRelease:
          - '--release 1.9.3'
          - '--release 1.12.1'
          - '--release 2.1.1'
          - '--release 2.3.5'
          - '--release 2.8.0'
          # Latest version
          - ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh
          npm i -g @zodern/mtest
      - name: Run Tests
        run: |
          # Retry tests since some of them are flaky
          mtest --package ./ --once ${{ matrix.meteorRelease }} || mtest --package ./ --once ${{ matrix.meteorRelease }}
